# -*- coding: utf-8 -*-
"""seminar01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CFP9T8b18U3sLql_TlldX50WntvVpP2t
"""

import numpy as np
import pandas as pd
from PIL import Image
import csv

image = Image.open("./image.png")
image = np.array(image, dtype=np.float32)

image /= 255.0

image_new = np.mean(image, axis=2)

data = pd.read_csv("./task.csv")
print(data)
row, col, length = int(data["row"][0]), int(data["col"][0]), int(data["len"][0])

p = image_new[row:row+length, col:col+length]

np.save('seminar01_crop.npy', p, allow_pickle=False)